name: Automated Preprocessing

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run preprocessing script
      run: python automate_Ghina.py
      working-directory: "Kriteria 1/preprocessing"

    - name: Commit processed dataset
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        if [ -n "$(git status --porcelain "Kriteria 1/preprocessing/dataset_preprocessing")" ]; then
          git add "Kriteria 1/preprocessing/dataset_preprocessing"
          git commit -m "Update processed dataset"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ghinaazi/Eksperimen_SML_Ghina.git HEAD:main
        else
          echo "No files to commit"
